# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cvtago-_O2THZhyTXOflD_N2xi1tup6r
"""

from google.colab import auth
auth.authenticate_user()

pip install --upgrade google-cloud

import os
os.environ["GOOGLE_CLOUD_PROJECT"] = "astral-net-472017-i3"

!gcloud services enable compute.googleapis.com
!gcloud services enable storage.googleapis.com

!gcloud config set project astral-net-472017-i3

!gcloud config get-value project

!gcloud services enable compute.googleapis.com
!gcloud services enable storage.googleapis.com
